### ISSUE TITLE
resources/deployment.yaml - needs rbac update for 1.18 kubernetes

### ISSUE THREAD

**Issue by fred-vogt** [proofpoint/kapprover#30]
k8s 1.18 has added a `signerName` field which requires additional permissions for `signers:approve`:
* https://kubernetes.io/docs/setup/release/notes/#kube-apiserver
  * https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/

Manifest:
* https://github.com/proofpoint/kapprover/blob/master/resources/deployment.yaml

Logs:
```
level=error ... user not permitted to approve requests with signerName "kubernetes.io/legacy-unknown"
```

For "legacy" requestors not setting the field such as [proofpoint/certificate-init-container](https://github.com/proofpoint/certificate-init-container)
```yaml
- apiGroups: ["certificates.k8s.io"]
  resources: [signers]
  resourceNames: ["kubernetes.io/legacy-unknown"]
  verbs: [approve]
```
